"""empty message

Revision ID: 134f0d331855
Revises: 9ebbd2f4727a
Create Date: 2023-08-18 10:36:16.666550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134f0d331855'
down_revision = '9ebbd2f4727a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(), nullable=True))
        batch_op.drop_column('description')
    #manually added for filling the existing data with the default value
    op.execute("UPDATE items SET origin = 'US'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
